// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: deliveryapi/pb/service.proto

package deliverypb

import (
	pb "github.com/stackus/ftgogo/serviceapis/commonapi/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_Pending   DeliveryStatus = 0
	DeliveryStatus_Scheduled DeliveryStatus = 1
	DeliveryStatus_Cancelled DeliveryStatus = 2
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "Pending",
		1: "Scheduled",
		2: "Cancelled",
	}
	DeliveryStatus_value = map[string]int32{
		"Pending":   0,
		"Scheduled": 1,
		"Cancelled": 2,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deliveryapi_pb_service_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_deliveryapi_pb_service_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_PickUp  ActionType = 0
	ActionType_DropOff ActionType = 1
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "PickUp",
		1: "DropOff",
	}
	ActionType_value = map[string]int32{
		"PickUp":  0,
		"DropOff": 1,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_deliveryapi_pb_service_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_deliveryapi_pb_service_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{1}
}

type Delivery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryID        string                 `protobuf:"bytes,1,opt,name=DeliveryID,proto3" json:"DeliveryID,omitempty"`
	RestaurantID      string                 `protobuf:"bytes,2,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
	AssignedCourierID string                 `protobuf:"bytes,3,opt,name=AssignedCourierID,proto3" json:"AssignedCourierID,omitempty"`
	Status            DeliveryStatus         `protobuf:"varint,4,opt,name=Status,proto3,enum=deliverypb.DeliveryStatus" json:"Status,omitempty"`
	PickUpAddress     *pb.Address            `protobuf:"bytes,5,opt,name=PickUpAddress,proto3" json:"PickUpAddress,omitempty"`
	DeliveryAddress   *pb.Address            `protobuf:"bytes,6,opt,name=DeliveryAddress,proto3" json:"DeliveryAddress,omitempty"`
	PickupTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=PickupTime,proto3" json:"PickupTime,omitempty"`
	ReadyBy           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ReadyBy,proto3" json:"ReadyBy,omitempty"`
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetDeliveryID() string {
	if x != nil {
		return x.DeliveryID
	}
	return ""
}

func (x *Delivery) GetRestaurantID() string {
	if x != nil {
		return x.RestaurantID
	}
	return ""
}

func (x *Delivery) GetAssignedCourierID() string {
	if x != nil {
		return x.AssignedCourierID
	}
	return ""
}

func (x *Delivery) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_Pending
}

func (x *Delivery) GetPickUpAddress() *pb.Address {
	if x != nil {
		return x.PickUpAddress
	}
	return nil
}

func (x *Delivery) GetDeliveryAddress() *pb.Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *Delivery) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *Delivery) GetReadyBy() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadyBy
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryID string                 `protobuf:"bytes,1,opt,name=DeliveryID,proto3" json:"DeliveryID,omitempty"`
	ActionType ActionType             `protobuf:"varint,2,opt,name=ActionType,proto3,enum=deliverypb.ActionType" json:"ActionType,omitempty"`
	Address    *pb.Address            `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	When       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=When,proto3" json:"When,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetDeliveryID() string {
	if x != nil {
		return x.DeliveryID
	}
	return ""
}

func (x *Action) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_PickUp
}

func (x *Action) GetAddress() *pb.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Action) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actions []*Action `protobuf:"bytes,1,rep,name=Actions,proto3" json:"Actions,omitempty"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{2}
}

func (x *Plan) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Courier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierID string `protobuf:"bytes,1,opt,name=CourierID,proto3" json:"CourierID,omitempty"`
	Plan      *Plan  `protobuf:"bytes,2,opt,name=Plan,proto3" json:"Plan,omitempty"`
	Available bool   `protobuf:"varint,3,opt,name=Available,proto3" json:"Available,omitempty"`
}

func (x *Courier) Reset() {
	*x = Courier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Courier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courier) ProtoMessage() {}

func (x *Courier) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courier.ProtoReflect.Descriptor instead.
func (*Courier) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{3}
}

func (x *Courier) GetCourierID() string {
	if x != nil {
		return x.CourierID
	}
	return ""
}

func (x *Courier) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Courier) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetCourierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierID string `protobuf:"bytes,1,opt,name=CourierID,proto3" json:"CourierID,omitempty"`
}

func (x *GetCourierRequest) Reset() {
	*x = GetCourierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierRequest) ProtoMessage() {}

func (x *GetCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierRequest.ProtoReflect.Descriptor instead.
func (*GetCourierRequest) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourierRequest) GetCourierID() string {
	if x != nil {
		return x.CourierID
	}
	return ""
}

type GetCourierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courier *Courier `protobuf:"bytes,1,opt,name=Courier,proto3" json:"Courier,omitempty"`
}

func (x *GetCourierResponse) Reset() {
	*x = GetCourierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierResponse) ProtoMessage() {}

func (x *GetCourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierResponse.ProtoReflect.Descriptor instead.
func (*GetCourierResponse) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCourierResponse) GetCourier() *Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

type SetCourierAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierID string `protobuf:"bytes,1,opt,name=CourierID,proto3" json:"CourierID,omitempty"`
	Available bool   `protobuf:"varint,2,opt,name=Available,proto3" json:"Available,omitempty"`
}

func (x *SetCourierAvailabilityRequest) Reset() {
	*x = SetCourierAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCourierAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCourierAvailabilityRequest) ProtoMessage() {}

func (x *SetCourierAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCourierAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*SetCourierAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetCourierAvailabilityRequest) GetCourierID() string {
	if x != nil {
		return x.CourierID
	}
	return ""
}

func (x *SetCourierAvailabilityRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type SetCourierAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool `protobuf:"varint,1,opt,name=Available,proto3" json:"Available,omitempty"`
}

func (x *SetCourierAvailabilityResponse) Reset() {
	*x = SetCourierAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCourierAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCourierAvailabilityResponse) ProtoMessage() {}

func (x *SetCourierAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCourierAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*SetCourierAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetCourierAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryID string `protobuf:"bytes,1,opt,name=DeliveryID,proto3" json:"DeliveryID,omitempty"`
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeliveryRequest) GetDeliveryID() string {
	if x != nil {
		return x.DeliveryID
	}
	return ""
}

type GetDeliveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delivery *Delivery `protobuf:"bytes,1,opt,name=Delivery,proto3" json:"Delivery,omitempty"`
}

func (x *GetDeliveryResponse) Reset() {
	*x = GetDeliveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deliveryapi_pb_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryResponse) ProtoMessage() {}

func (x *GetDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deliveryapi_pb_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_deliveryapi_pb_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeliveryResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

var File_deliveryapi_pb_service_proto protoreflect.FileDescriptor

var file_deliveryapi_pb_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x03, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x0d, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x3a, 0x0a, 0x0a, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x42, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x42, 0x79, 0x22, 0xbd, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44, 0x12, 0x36, 0x0a,
	0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x57, 0x68, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x57, 0x68,
	0x65, 0x6e, 0x22, 0x34, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x2c, 0x0a, 0x07, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x6b, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x24, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x31, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x07, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x22, 0x5b, 0x0a,
	0x1d, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x3e, 0x0a, 0x1e, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x34, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x44,
	0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52,
	0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2a, 0x3b, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x2a, 0x25, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x6b, 0x55, 0x70, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x4f, 0x66, 0x66, 0x10, 0x01, 0x32, 0x9f, 0x02,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f,
	0x0a, 0x16, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x29, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12, 0x1e,
	0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x75, 0x73, 0x2f, 0x66, 0x74, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x3b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deliveryapi_pb_service_proto_rawDescOnce sync.Once
	file_deliveryapi_pb_service_proto_rawDescData = file_deliveryapi_pb_service_proto_rawDesc
)

func file_deliveryapi_pb_service_proto_rawDescGZIP() []byte {
	file_deliveryapi_pb_service_proto_rawDescOnce.Do(func() {
		file_deliveryapi_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_deliveryapi_pb_service_proto_rawDescData)
	})
	return file_deliveryapi_pb_service_proto_rawDescData
}

var file_deliveryapi_pb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_deliveryapi_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_deliveryapi_pb_service_proto_goTypes = []interface{}{
	(DeliveryStatus)(0),                    // 0: deliverypb.DeliveryStatus
	(ActionType)(0),                        // 1: deliverypb.ActionType
	(*Delivery)(nil),                       // 2: deliverypb.Delivery
	(*Action)(nil),                         // 3: deliverypb.Action
	(*Plan)(nil),                           // 4: deliverypb.Plan
	(*Courier)(nil),                        // 5: deliverypb.Courier
	(*GetCourierRequest)(nil),              // 6: deliverypb.GetCourierRequest
	(*GetCourierResponse)(nil),             // 7: deliverypb.GetCourierResponse
	(*SetCourierAvailabilityRequest)(nil),  // 8: deliverypb.SetCourierAvailabilityRequest
	(*SetCourierAvailabilityResponse)(nil), // 9: deliverypb.SetCourierAvailabilityResponse
	(*GetDeliveryRequest)(nil),             // 10: deliverypb.GetDeliveryRequest
	(*GetDeliveryResponse)(nil),            // 11: deliverypb.GetDeliveryResponse
	(*pb.Address)(nil),                     // 12: commonpb.Address
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
}
var file_deliveryapi_pb_service_proto_depIdxs = []int32{
	0,  // 0: deliverypb.Delivery.Status:type_name -> deliverypb.DeliveryStatus
	12, // 1: deliverypb.Delivery.PickUpAddress:type_name -> commonpb.Address
	12, // 2: deliverypb.Delivery.DeliveryAddress:type_name -> commonpb.Address
	13, // 3: deliverypb.Delivery.PickupTime:type_name -> google.protobuf.Timestamp
	13, // 4: deliverypb.Delivery.ReadyBy:type_name -> google.protobuf.Timestamp
	1,  // 5: deliverypb.Action.ActionType:type_name -> deliverypb.ActionType
	12, // 6: deliverypb.Action.Address:type_name -> commonpb.Address
	13, // 7: deliverypb.Action.When:type_name -> google.protobuf.Timestamp
	3,  // 8: deliverypb.Plan.Actions:type_name -> deliverypb.Action
	4,  // 9: deliverypb.Courier.Plan:type_name -> deliverypb.Plan
	5,  // 10: deliverypb.GetCourierResponse.Courier:type_name -> deliverypb.Courier
	2,  // 11: deliverypb.GetDeliveryResponse.Delivery:type_name -> deliverypb.Delivery
	6,  // 12: deliverypb.DeliveryService.GetCourier:input_type -> deliverypb.GetCourierRequest
	8,  // 13: deliverypb.DeliveryService.SetCourierAvailability:input_type -> deliverypb.SetCourierAvailabilityRequest
	10, // 14: deliverypb.DeliveryService.GetDelivery:input_type -> deliverypb.GetDeliveryRequest
	7,  // 15: deliverypb.DeliveryService.GetCourier:output_type -> deliverypb.GetCourierResponse
	9,  // 16: deliverypb.DeliveryService.SetCourierAvailability:output_type -> deliverypb.SetCourierAvailabilityResponse
	11, // 17: deliverypb.DeliveryService.GetDelivery:output_type -> deliverypb.GetDeliveryResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_deliveryapi_pb_service_proto_init() }
func file_deliveryapi_pb_service_proto_init() {
	if File_deliveryapi_pb_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deliveryapi_pb_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delivery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Courier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCourierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCourierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCourierAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCourierAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeliveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deliveryapi_pb_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeliveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deliveryapi_pb_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deliveryapi_pb_service_proto_goTypes,
		DependencyIndexes: file_deliveryapi_pb_service_proto_depIdxs,
		EnumInfos:         file_deliveryapi_pb_service_proto_enumTypes,
		MessageInfos:      file_deliveryapi_pb_service_proto_msgTypes,
	}.Build()
	File_deliveryapi_pb_service_proto = out.File
	file_deliveryapi_pb_service_proto_rawDesc = nil
	file_deliveryapi_pb_service_proto_goTypes = nil
	file_deliveryapi_pb_service_proto_depIdxs = nil
}
